---
title: "functional_diversity_cgcs"
output: html_document
date: "2024-07-21"
---

### resources for calculations
https://cran.r-project.org/web/packages/fundiversity/vignettes/fundiversity.html 
# does not work for n > 16 traits

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Load packages
library(tidyverse)
library(sf)
library(FD)
library(data.table)
install.packages("fundiversity")

data(package = "fundiversity")
```

### prep trait data
```{r}
### open data
dat_trait <- read.csv("C:/Users/krist/Downloads/nfi_trait_dat_clean.csv")

### simplify data
dat_trait_simp <- dat_trait %>%
  dplyr::select(species,
                trait_name,
                try_species_id,
                try_trait_id,
                value,
                unit,
                value_kind,
                location) #removed common name, number of observations, orig_ref
trait_summ <- dat_trait_simp %>%
  group_by(try_species_id, try_trait_id) %>%
  summarise(n_surveyed = length(unique(value)))


### form species-trait matrix (reshape data)
trait_wide <- dat_trait_simp %>%
  dplyr::select(species, trait_name, value)

trait_wide <- trait_wide %>%
  pivot_wider(names_from = trait_name,
              values_from = value)

### make dispersal syndrome numeric



```

### prep time data
```{r}
### number of time-period observations per plot
install.packages("lubridate")

trait_summ <- wcan_biomass_total %>%
  group_by(nfi_plot) %>%
  summarise(n_surveyed = length(unique(meas_date)))
table(trait_summ$n_surveyed)
# 17 surveyed once, 378 surveyed twice, 36 surveyed three times

### drop plots surveyed once
once <- c("1100981", "1114666", "1128941","1162841","1218396","1225241","1232216", "1273466", "1279961", "1294161", "1328041", "1335371", "1410761", "1424456", "1445166", "1452066")

wcan_dat <- wcan_biomass_total %>%
  filter(!nfi_plot %in% once)

### simplify data
wcan_dat_simp <- wcan_dat %>%
  dplyr::select(nfi_plot,
                meas_date,
                NFI_species,
                biomass_composition) %>%
  group_by(nfi_plot,
           meas_date,
           NFI_species,
           biomass_composition)
                

### add survey numbers to data
wcan_dat <- merge(wcan_dat_simp,
                  trait_summ,
                  by = "nfi_plot")

### change meas_date to ymd form
library("lubridate")

wcan_dat$meas_date <- ymd(wcan_dat$meas_date)

### set t(min) and t(max)
trait_t <- wcan_dat %>%
  group_by(nfi_plot) %>%
  summarise(min_year = min(meas_date),
            max_year = max(meas_date))

### merge with wcan_dat
wcan_dat <- merge(wcan_dat,
                  trait_t,
                  by = "nfi_plot")

### add time steps
wcan_dat <- wcan_dat %>%
  mutate(time_step = ifelse(meas_date ==min_year, "t1",
                            ifelse(meas_date == max_year & n_surveyed == 2, "t2",
                                   ifelse(meas_date == max_year & n_surveyed == 3, "t3", 
                                          "t2"))))
wcan_dat <- wcan_dat %>%
  mutate(meas_year = year(ymd(wcan_dat$meas_date)))

### df of time step and plots
wcan_time_step <- wcan_dat %>%
  dplyr::select(nfi_plot, meas_date, time_step, meas_year) %>%
  distinct()
write.csv(wcan_time_step, "wcan_time_step.csv")

### make df for t1 plots
wcan_t1 <- wcan_dat %>%
  filter(time_step == "t1")

wcan_t1 <- wcan_t1 %>%
  dplyr::select(nfi_plot,
                meas_date,
                NFI_species,
                time_step,
                biomass_composition,
                meas_year)

### total biomass per plot
plot_biomass_tot <- wcan_t1 %>%
  group_by(nfi_plot, meas_date) %>%
  summarise(total_biomass_plot = sum(biomass_composition))

### merge 
wcan_t1 <- merge(wcan_t1, plot_biomass_tot,
                 by = c("nfi_plot", "meas_date"))

### percent biomass (per plot)
wcan_t1 <- wcan_t1 %>%
  mutate(pct_biomass = biomass_composition/total_biomass_plot)

### save as csv
write.csv(wcan_t1, "wcan_t1.csv")
```

### reformat traits
```{r}
### open nfi traits file
trait_dat_clean_sp <- read.csv("C:/Users/krist/Downloads/nfi_trait_dat_clean_sp.csv")

### select necessary columns
trait_dat <- trait_dat_clean_sp %>%
  dplyr::select(vect_sp_codes, try_species_id,
                trait_name, try_trait_id,
                value
                )
unique(trait_dat$trait_name)

### make dispersal syndrome numeric
dispersal <- filter(trait_dat, trait_name == "dispersal syndrome") 
unique(dispersal$value) # lists unique dispersal syndrome methods

trait_dat$value[trait_dat$value == "animals, general"] <- 2
trait_dat$value[trait_dat$value == "birds"] <- 2
trait_dat$value[trait_dat$value == "mammals"] <- 2
trait_dat$value[trait_dat$value == "human"] <- 2
trait_dat$value[trait_dat$value == "water"] <- 3
trait_dat$value[trait_dat$value == "wind and water"] <- 4
trait_dat$value[trait_dat$value == "wind"] <- 6

### make leaf texture (coarseness) numeric
trait_dat$value[trait_dat$value == "fine"] <- 0
trait_dat$value[trait_dat$value == "medium"] <- 1
trait_dat$value[trait_dat$value == "coarse"] <- 2

### make Leaf texture (sclerophylly, physical strength, toughness) numeric
trait_dat$value[trait_dat$value == "always mesomorphic"] <- 0

### make foliage type (deciduous or evergreen) numeric
trait_dat$value[trait_dat$value == "evergreen"] <- 3
trait_dat$value[trait_dat$value == "evergreen but drought deciduous"] <- 2
trait_dat$value[trait_dat$value == "semi-evergreen"] <- 1
trait_dat$value[trait_dat$value == "deciduous"] <- 0

### make coarse root rooting depth numeric
trait_dat$value[trait_dat$value == "shallow"] <- 0
trait_dat$value[trait_dat$value == "shallow_moderate"] <- 1
trait_dat$value[trait_dat$value == "varying"] <- 2
trait_dat$value[trait_dat$value == "deep"] <- 3

### make clonal growth numeric
trait_dat$value[trait_dat$value == "underground"] <- 3
trait_dat$value[trait_dat$value == "basal"] <- 2
trait_dat$value[trait_dat$value == "abovegound"] <- 1
trait_dat$value[trait_dat$value == "none"] <- 0

### make cone serotiny numeric
trait_dat$value[trait_dat$value == "non-serotinous"] <- 0
trait_dat$value[trait_dat$value == "variable"] <- 1
trait_dat$value[trait_dat$value == "serotinous and semi-serotinous"] <- 2
trait_dat$value[trait_dat$value == "serotinous"] <- 3

### make clonal growth form numeric
trait_dat$value[trait_dat$value =="roots with adventitious buds"] <- 0
trait_dat$value[trait_dat$value == "root suckers"] <- 2
trait_dat$value[trait_dat$value == "root crown, root suckers"] <- 1
trait_dat$value[trait_dat$value == "root crown"] <- 1
trait_dat$value[trait_dat$value == "layering, rooting of fallen branches, fallen trunks"] <- 3
trait_dat$value[trait_dat$value == "layering, root collar"] <- 3
trait_dat$value[trait_dat$value == "layering, branches, stems"] <- 3
trait_dat$value[trait_dat$value == "layering"] <- 3
trait_dat$value[trait_dat$value == "epicormic shoots (coppice shoots)"] <- 4
trait_dat$value[trait_dat$value == "basal sprouts"] <- 2

### make degress of self-pruning numeric
trait_dat$value[trait_dat$value == "moderate"] <- 0
trait_dat$value[trait_dat$value == "high"] <- 1

### make fire_tolerance numeric
trait_dat$value[trait_dat$value == "low"] <- 0
trait_dat$value[trait_dat$value == "moderate"] <- 1
trait_dat$value[trait_dat$value == "high"] <- 2

### make leaf flammability numeric
trait_dat$value[trait_dat$value == "low"] <- 0
trait_dat$value[trait_dat$value == "moderate"] <- 1
trait_dat$value[trait_dat$value == "high"] <- 2

### make seed bank longevity numeric
trait_dat$value[trait_dat$value == "0.25-1"] <- 0
trait_dat$value[trait_dat$value == "< 1"] <- 0
trait_dat$value[trait_dat$value == "1-5"] <- 1
trait_dat$value[trait_dat$value == "3-5"] <- 2
trait_dat$value[trait_dat$value == ">5"] <- 3

trait_dat$value <- as.numeric(trait_dat$value)

write.csv(trait_dat, "trait_dat_num.csv")

### collect the mean values of each trait per species
trait_dat_mean <- trait_dat %>%
  group_by(vect_sp_codes, try_species_id, trait_name) %>%
  summarise(trait_mean = mean(value))
write.csv(trait_dat_mean, "trait_dat_mean.csv")


```


```{r}
### forms site-species matrix (reshape data)
site_dat <- read.csv("our_data/biomass_materials/wcan_biomass_total.csv")

site_dat_simp <- site_dat %>%
  dplyr::select(NFI_species,
                nfi_plot,
                meas_date,
                biomass_composition) #removed utm_n, utm_e
site_summ <- site_dat_simp %>%
  group_by(NFI_species, nfi_plot) %>%
  summarise(n_surveyed = length(unique(biomass_composition)))

site_wide <- site_summ %>%
  dplyr::select(NFI_species, nfi_plot, n_surveyed)

site_wide <- site_wide %>%
  pivot_wider(names_from = NFI_species,
              values_from = n_surveyed)

### change NA ->0
site_wide[is.na(site_wide)] <- 0


```

