---
title: "check_data"
output:
  pdf_document: default
  html_document: default
date: "2024-06-11"
---

## Description
Code to check if Maynard et al. data includes environmental data and phylogeny for the species we're using.

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### load libraries
library(tidyverse)
```

## Open Maynard raw data
```{r}
## open species lookup table -- weird numbering system for species and genus
sp_lookup <- read.csv("data/raw_data/ANGIO_GYMNO_lookup.csv")

### open phylogenetic eigenvectors
phylo_eigen <- read.csv("data/raw_data/Phylogenetic_eigenvectors.csv")

### open env_names
env_names <- read.csv("data/raw_data/env_names.csv")

### open environmental covariates
env_cov <- read.csv("data/raw_data/Environmental_covariates.csv")

### trait names
trait_names <- read.csv("data/raw_data/Trait_names.csv")

### phylog tree
phylo_tree <- ReadTntTree("data/raw_data/dichotomous_phylogenetic_tree.tree")

### imputed trait data
imputed_dat <- read.csv("data/results/Imputed_trait_data.csv")
```

## Prep our trait data
### fix lat/lon
```{r}
### open data
trait_dat <- read.csv("our_data/CGCS_Canada_traits_6_11.csv")

### how many have coordinates?
trait_dat_coords <- trait_dat %>%
  filter(!location == "")

### clean up location column
trait_dat_coords <- trait_dat_coords %>%
  
  ### get rid of locations missing lat/lon
  filter(!(location %in% c("USA",
                        "Russia",
                        "Netherlands",
                        "Germany"))) %>%
  filter(!location %in% c("34924","34924 (Essex)")) %>%
  
  ### fix the one with a period instead of a comma
  mutate(location = ifelse(location == "45.76667. -89.56667",
         "45.76667,-89.56667",
         location))

### make latitude and longitude columns
trait_dat_coords <- trait_dat_coords %>%
  separate_wider_delim(location, ",", names = c("latitude",
                                                "longitude"))

### clean up lat and lon columns
trait_dat_coords <- trait_dat_coords %>%
  
  ### fix -92.87Lusk and Reich (2000)
  mutate(orig_ref = ifelse(longitude == " -92.87Lusk and Reich (2000)",
                           "Lusk and Reich (2000)",
                           orig_ref),
         longitude = ifelse(longitude == " -92.87Lusk and Reich (2000)",
                            "-92.87",
                            longitude)) %>%
  
  ### fix some more
  mutate(longitude = ifelse(longitude == "-122 (Oregon)",
                            "-122",
                            longitude),
         longitude = ifelse(longitude == " -122.1 (OR)",
                            "-122.1",
                            longitude),
         longitude = ifelse(longitude == " -124.3 (WA)",
                            "-124.3",
                            longitude),
         longitude = ifelse(longitude == " -121.7 (Oregon)",
                            "-121.7",
                            longitude),
         longitude = ifelse(longitude == " -121.5 (OR)",
                            "-121.5",
                            longitude),
         longitude = ifelse(longitude == " -124 (OR)",
                            "-124",
                            longitude),
         longitude = ifelse(longitude == " -121.6 (OR)",
                            "-121.6",
                            longitude),
         longitude = ifelse(longitude == " -124.1 (OR)",
                            "-124.1",
                            longitude),
         longitude = ifelse(longitude == " -122.1 (OR)",
                            "-122.1",
                            longitude),
         longitude = ifelse(longitude == " 27.6 (Belarus)",
                            "27.6",
                            longitude))

### convert decimal/minutes
trait_dat_coords <- trait_dat_coords %>%
    mutate(longitude = ifelse(longitude == " 83h 22m",
                            "-83.36666667",
                            longitude),
           latitude = ifelse(latitude == "46h 25m",
                             "46.41666667",
                             latitude),
           longitude = ifelse(longitude == " 79d 27m W",
                            "-79.45",
                            longitude),
           latitude = ifelse(latitude == "48d 30m N",
                             "48.5",
                             latitude),
           longitude = ifelse(longitude == " 83h 22m",
                              "-83.3666667",
                              longitude),
           longitude = ifelse(longitude == " 79d 27m W",
                              "-79.45",
                              longitude),
           latitude = ifelse(orig_ref == "Sodhi, DS,  Livingstone, SW,  Carboni, M,  Cadotte, MW.  Plant invasion alters trait composition and diversity across habitats. Ecol Evol.  2019; 9: 6199– 6210. https://doi.org/10.1002/ece3.5130",
                           "43.82047222",
                           latitude),
         longitude = ifelse(orig_ref == "Sodhi, DS,  Livingstone, SW,  Carboni, M,  Cadotte, MW.  Plant invasion alters trait composition and diversity across habitats. Ecol Evol.  2019; 9: 6199– 6210. https://doi.org/10.1002/ece3.5130",
                           "-79.15950556",
                           longitude),
         latitude = ifelse(latitude == "45d 54m 45.9s N",
                           "45.91275",
                           latitude),
         longitude = ifelse(longitude == " 73d 17m 12.8s W",
                            "-73.28688889", 
                            longitude),
           latitude = ifelse(orig_ref == "Auger, S., Shipley, B. (2012). : Interspecific and intraspecific trait variation along short environmental gradients in an old-growth temperate forest.  Journal of Vegetation Science. DOI: 1111/j.1654-1103.2012.01473.x",
                           "45.55058872985592",
                           latitude),
         longitude = ifelse(orig_ref == "Auger, S., Shipley, B. (2012). : Interspecific and intraspecific trait variation along short environmental gradients in an old-growth temperate forest.  Journal of Vegetation Science. DOI: 1111/j.1654-1103.2012.01473.x",
                           "-73.17601570975708",
                           longitude),
         orig_ref = ifelse(longitude == " -92.87Lusk and Reich (2000)",
                           "Lusk and Reich (2000)",
                           orig_ref),
         longitude = ifelse(longitude == " -92.87Lusk and Reich (2000)",
                           "-92.87",
                           longitude),
         longitude = ifelse(longitude == " -71.1-6599",
                            "-71.16599",
                            longitude),
         latitude = ifelse(latitude == "35.-0213",
                           "35.0213",
                           ifelse(latitude == "47.-77262",
                                  "47.77262",
                                  latitude)))

### convert to numeric
trait_dat_coords <- trait_dat_coords %>%
  mutate(lat_numeric = as.numeric(latitude),
         long_numeric = as.numeric(longitude))
```

### fix trait names
```{r}
### open try trait table (IDs and names)
try_ids <- read.csv("data/raw_data/try_trait_id_table.csv")

### simplify and change column names
try_ids <- try_ids %>%
  dplyr::select(try_trait_id = TraitID,
                trait_name = Trait)

### subset trait_dat_coords based on whether or not there are trait names
trait_dat_1 <- trait_dat_coords %>%
  filter(!trait_name == "")
trait_dat_2 <- trait_dat_coords %>%
  filter(trait_name == "")

### drop trait name from trait_dat_2
trait_dat_2 <- trait_dat_2 %>%
  dplyr::select(-trait_name)

### merge in trait names for trait_dat_2
trait_dat_2 <- merge(x = trait_dat_2,
                     y = try_ids,
                     by = "try_trait_id",
                     all.x = TRUE)

### fix column order
trait_dat_2 <- trait_dat_2 %>%
  dplyr::select(species, common_name,
                trait_name, try_species_id,
                try_trait_id, value,
                unit, value_kind, number_of_observations,
                latitude, longitude, orig_ref,
                try_notes, lat_numeric, long_numeric)

### combine
trait_dat_coords <- rbind(trait_dat_1,
                          trait_dat_2)

### shorten trait names
trait_dat_coords <- trait_dat_coords %>%
  mutate(trait_name_short = ifelse(trait_name == "Xylem water potential at which 50% of conductivity is lost (P50)", "xylem_p50", ifelse(trait_name == "Xylem embolism: Shape parameter for the vulnerability curve, a", "xylem_embolism", ifelse(trait_name == "Plant height vegetative", "plant_height_veg", ifelse(trait_name == "water potential 50% loss of conductivity (MPa)", "water_potential_50", ifelse(trait_name == "Leaf dry matter content per leaf water-saturated mass (LDMC)", "ldmc_water", ifelse(trait_name == "Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)", "ldmc_fresh", ifelse(trait_name == "Plant growth rate relative (plant relative growth rate, RGR)", "plant_rel_growth_rate", ifelse(trait_name == "Leaf texture (sclerophylly, physical strength, toughness)", "leaf_texture", ifelse(trait_name == "Stem specific density (SSD, stem dry mass per stem fresh volume) or wood density", "stem_specific_density", ifelse(trait_name == "Bark thickness", "bark_thick", ifelse(trait_name == "Dispersal syndrome", "disp_syndrome", ifelse(trait_name == "Stomata conductance per leaf area", "stomata_conduct", ifelse(trait_name == "Photosynthesis: intercellular CO2 concentration", "photosynth_co2", ifelse(trait_name == "Photosynthesis rate per leaf area", "photosynth_rate", ifelse(trait_name == "Stomata density", "stomata_dens", ifelse(trait_name == "Stem conduit density (vessels and tracheids)", "stem_conduit_dens", ifelse(trait_name == "Stem conduit diameter (vessels, tracheids)", "stem_conduit_diam", ifelse(trait_name == "Plant height of lowest branch", "height_lowest_branch", ifelse(trait_name == "Xylem hydraulic vulnerability, xylem cavitation vulnerability, embolism vulnerability, (P20, P50, P8", "xylem_hydraul_vuln", ifelse(trait_name == "Plant resprouting capacity", "resprout_capacity", ifelse(trait_name == "Leaf area-specific conductivity (leaf specific conductivity)", "leaf_area_conduct", ifelse(trait_name == "Wood vessel density", "wood_vessel_dens", ifelse(trait_name == "Wood vessel diameter", "wood_vessel_diam", ifelse(trait_name == "Plant height generative", "plant_height_gen", ifelse(trait_name == "Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): undefined if petiole is in- or exclu", "specific_leaf_area", ifelse(trait_name == "Plant biomass and allometry: Leaf dry mass per plant", "leaf_dry_mass_plant", trait_name)))))))))))))))))))))))))))
```

### reshape to match Imputed_trait_data.csv
```{r}
### simplify cols
trait_ref <- trait_dat_coords %>%
  dplyr::select(LAT = lat_numeric,
                LON = long_numeric,
                accepted_bin = species,
                trait_name_short,
                value)

### remove wind/long-distance (disp_syndrome) and "yes" (resprout_capacity, wood_vessel_dens, wood_vessel_diam)
trait_ref <- trait_ref %>%
  filter(!value %in% c("yes", "wind/long-distance"))

### convert value to numeric
trait_ref <- trait_ref %>%
  mutate(value_num = as.numeric(value))

### get mean values for observations from the same lat/long
trait_ref <- trait_ref %>%
  group_by(LAT, 
           LON, 
           accepted_bin,
           trait_name = trait_name_short) %>%
  summarise(mean_value = mean(value_num, na.rm = TRUE))

### change column names
trait_ref <- trait_ref %>%
  dplyr::select(LAT,
                LON,
                trait_name, 
                mean_value,
                accepted_bin) 

### are there duplicate rows?
trait_ref <- trait_ref %>%
  distinct()

### reshape
trait_ref <- trait_ref %>%
  pivot_wider(names_from = trait_name,
              values_from = mean_value)

### reorder cols
trait_final <- trait_ref %>%
  dplyr::select(LAT, LON,
                specific_leaf_area:xylem_p50,
                leaf_dry_mass_plant:stomata_dens,
                accepted_bin)

### write out
write_csv(trait_final,
          "our_data/cgcs_canada_reshaped.csv")
```


