---
title: "BC biomass merged"
output: html_document
date: "2024-07-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
summary(cars)
```



```{r pressure, echo=FALSE}
plot(pressure)
```

### sum of biomass for each nfi plot (ltp)
```{r}
### open large tree plot tree file
BC_ltp_tree <- read.csv("C:/Users/krist/Downloads/CGCS KH/relevant_time_data/bc_gp_ltp_tree.csv")

names(BC_ltp_tree)

### select only relevant data columns
BC_ltp_biomass <- select(BC_ltp_tree, nfi_plot, meas_date, meas_num, biomass_total)

### replace NA values as 0
BC_ltp_biomass[is.na(BC_ltp_biomass)] <- 0

### biomass sums grouped by nfi plot and meas_date
BC_ltp_biomass_sum <- BC_ltp_biomass %>%
  group_by(nfi_plot, meas_date) %>%
  summarise(biomass_total =sum(biomass_total))

```
### merge biomass summary and resurveyed files (ltp)
```{r}
names(BC_ltp_biomass_sum)
names(BC_ltp_resurveyed)

### check similarities between file headers
intersect(names(BC_ltp_biomass_sum), names(BC_ltp_resurveyed))

### merge the files based on nfi plot and meas_date
BC_ltp_biomass_merged <- merge(BC_ltp_biomass_sum, BC_ltp_resurveyed) %>%
  mutate(percent / 100) %>% # divide percent by 100 to obtain decimal value
  mutate(percent/100 * biomass_total) # multiple decimal percent by total bioimass to obtain biomass per species

### rename additional column
colnames(BC_ltp_biomass_merged)[16] <- "biomass_composition"

### remove unnecessary columns
BC_ltp_biomass_merged$...1 <- NULL

### save as csv
write.csv(BC_ltp_biomass_merged, "BC_ltp_biomass_merged.csv")

```

### introducing diversity, evenness, and richness indexes (ltp)
```{r}
BC_ltp_header <- read.csv("C:/Users/krist/Downloads/CGCS KH/relevant_time_data/bc_gp_ltp_header.csv")

### select only relevant columns
names(BC_ltp_header)

BC_ltp_index <- select(BC_ltp_header, nfi_plot, meas_date, meas_num, bindex_ltshannon, bindex_lteven, bindex_ltmargalef)

### replace NA values as 0
BC_ltp_index[is.na(BC_ltp_index)] <- 0

```


### sum of biomass for each nfi plot (stp)
```{r}
### open stp tree files
BC_stp_tree <-read.csv("C:/Users/krist/Downloads/CGCS KH/relevant_time_data/bc_gp_stp_tree.csv")

names(BC_stp_tree)

### select relevant data columns
BC_stp_biomass <- select(BC_stp_tree, nfi_plot, meas_date, meas_num, smtree_biomass)

### biomass sums grouped by nfi plot and meas_date
BC_stp_biomass_sum <- BC_stp_biomass %>%
  group_by(nfi_plot, meas_date) %>%
  summarise(smtree_biomass =sum(smtree_biomass))
```


### merge biomass summary and resurveyed files
```{r}
names(BC_stp_resurveyed)
names(BC_stp_biomass_sum)

### check similarities between file headers
intersect(names(BC_stp_resurveyed), names(BC_stp_biomass_sum))

### merge files based on nfi plot and meas_date
BC_stp_biomass_merged <- merge(BC_stp_biomass_sum, BC_stp_resurveyed) %>%
  mutate(smtree_percent / 100) %>%
  mutate(smtree_percent/100 * smtree_biomass)

### save as csv
write.csv(BC_stp_biomass_merged, "BC_stp_biomass_merged.csv")
```

### introducing diversity, evenness, and richness indexes (stp)
```{r}
BC_stp_header <- read.csv("C:/Users/krist/Downloads/CGCS KH/relevant_time_data/bc_gp_stp_header.csv")

### select relevant columns
names(BC_stp_header)

BC_stp_index <- select(BC_stp_header, nfi_plot, meas_date, meas_num, bindex_stshannon, bindex_steven, bindex_stmargalef)

### replace NA with 0
BC_stp_index[is.na(BC_stp_index)] <- 0
```

### merge index files
```{r}
BC_indeces <- merge(BC_ltp_index, BC_stp_index)

write.csv(BC_indeces, "BC_indeces.csv")


```

